### ISSUE TITLE
init.py doing a whole lot of things it shouldn't, liable to break users install envs

### ISSUE THREAD

**Issue by mcmonkey4eva** [NimaNzrii/comfyui-photoshop#123]
https://github.com/NimaNzrii/comfyui-photoshop/blob/cb17df9f7da7114e2d41ee411de74de334752492/__init__.py

Just about everything in this file ranges from "the wrong method" to "utterly deranged and actively _trying_ to break things"

- Why is there code to actively destroy `venv`s?!
- the `python -m pip install` commands are missing `-s` which is required to not break envs
- why are you running pip commands on every boot anyway!?
- please just let Comfy Manager handle dependencies
- all of this crazy code is for a dependency on *one single pip package*??
- `sys.path.append(py_path)` *what*
- `os.chdir(py_path)` **WHAT**
- this is almost redundant to tack on, but: you have 3 nodes in total, you do not need the chaotic dynamic import logic
- the entire `__init__.py` file should be about 3 lines long in total. All the rest does not belong at all

**Comment by SouthbayJay** [comment]
![Screenshot 2024-06-27 144631](https://github.com/NimaNzrii/comfyui-photoshop/assets/131290832/d365b24b-ce69-49bb-97b1-d199ca0429ce)

**Comment by NimaNzrii** [comment]
Mostly you are Right.

Let me explain smt for you
In version 1.0.0 our method was different , we have created venv folder and we had to install a lot of libraries. And many times it didn't worked so we have added a lit bit complex method to upgrade pip and clear cache and all of these stuffs to make sure all libs are installing 

But in V1.4.0 we changed the method , no need the to create a venv and everything working smoother and needs less library and etc...
So it will remove the old venv method only for users who updated from v1 to v1.4!

About os.chdir(py_path) it basically change the dir temporarily and then will restore to default dir , abd the reson is to launch the backend.py inside of the plugin dir , otherwise the backend.py will look at ComfyUi default python library folder!

At the end, you are completely right, the code can be cleaned up a lot in the init.py 
Will work on it
@mcmonkey4eva

**Comment by NimaNzrii** [comment]
> https://github.com/NimaNzrii/comfyui-photoshop/blob/cb17df9f7da7114e2d41ee411de74de334752492/__init__.py
> 
> Just about everything in this file ranges from "the wrong method" to "utterly deranged and actively _trying_ to break things"
> 
> * Why is there code to actively destroy `venv`s?!
> * the `python -m pip install` commands are missing `-s` which is required to not break envs
> * why are you running pip commands on every boot anyway!?
> * please just let Comfy Manager handle dependencies
> * all of this crazy code is for a dependency on _one single pip package_??
> * `sys.path.append(py_path)` _what_
> * `os.chdir(py_path)` **WHAT**
> * this is almost redundant to tack on, but: you have 3 nodes in total, you do not need the chaotic dynamic import logic
> * the entire `__init__.py` file should be about 3 lines long in total. All the rest does not belong at all

Will update these old codes soon:)) 
Thanks for your attention!
U Such a great person

**Comment by NimaNzrii** [comment]
Fixed mate
