### ISSUE TITLE
The mask output from the main node is not correct

### ISSUE THREAD

**Issue by sdk401** [NimaNzrii/comfyui-photoshop#27]
I've noticed the mask output of the main plugin node gives the mask with R1 G1 B1 values on the "black" area. So we are getting the whole photoshop canvas as masked area. Maybe this is the intended behavior, but I can't understand the reason for this.

I've saved mask as image and opened it in photoshop to check, I'm including the screenshot.

![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/162196217/bdf79282-513a-4cad-ac1f-643e46d5a2e6)

I can solve this problem in my workflow by converting mask to image and rising levels slightly, so it's not a deal breaker, but still.

**Comment by NimaNzrii** [comment]
I'm so impressed that you found this bug. I dont know either about this bug , but i think it might be on saving input as jpg
I'm gonna test webp for a smoother and better result next updates

**Comment by sdk401** [comment]
> saving input as jpg

oh, that's why I also see the jpeg artifacts in final image :)
if you can change it to png or some other lossless format, this will be much appreciated :)

**Comment by NimaNzrii** [comment]
> > saving input as jpg
> 
> oh, that's why I also see the jpeg artifacts in final image :)
> if you can change it to png or some other lossless format, this will be much appreciated :)

Hemm
So that would be an important update
So it can be like an option to select format on the settings

**Comment by sdk401** [comment]
Well, it can be an option, but I can't think of any reason to choose lossy format over lossless. 

I'm attaching zoomed image with jpef artifacts, look at the small hair and bubbles. Why would anyone want this option? :)
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/162196217/ebbd600d-111d-4c5e-b62c-04d8f3dcb9d1)

Also i think when converting to jpeg colors change slightly, it's no big deal when generating from scratch, but it is noticeable when inpainting.

**Comment by dt126** [comment]
I was going to report this issue as well, but then I found it had already been reported. I am trying to create custom inpatining workflows using a series of nodes called, "Crop and Stitch" from the Github below (and forks). https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch

These nodes could be very useful with yours when working on photos (which tend to be pretty large). The nodes will autocrop the image relative to the mask (based on settings) and then re-stitch it together. This is similar to functionality in the base A1111 inpainting module. For example, I could select an area maybe 300 X 600 px out of an image that is 4000 X 7000 and these nodes will crop the mask and image to something more reasonable based on processing power (perhaps 450 X 750), whereas your standard inpainting workflow would try to in-paint a 300X600 area onto the entire 4000X7000 image. 

However, when I try to use the mask from your node, it gives an error that the mask output is a list. I can get around this by inserting a "Mask to Image" and then "Image to Mask" nodes (or directly accessing the PS_Mask.png file your node creates), but since blacks are 1,1,1 instead of 0,0,0, it doesn't work correctly. In experimenting, have found at least one other mask operations node, "Expand Mask," that has the same issue.

Is there any solution that you've though of for this issue?

Thank you, very much. I really like your nodes so far, there work very well with PS.

**Comment by NimaNzrii** [comment]
Update the node and it will fix❤️
